// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appDragTitle': string;
  'container': string;
  'icon': string;
  'iconSetting': string;
  'item': string;
  'pannel': string;
  'txt': string;
}
export const cssExports: CssExports;
export default cssExports;
