// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addnew': string;
  'container': string;
  'control': string;
  'iconAdd': string;
  'iconBlock': string;
  'iconBlockSelected': string;
  'iconCanlendar': string;
  'iconCanlendarSelected': string;
  'iconCheck': string;
  'iconDetail': string;
  'iconDetailSelected': string;
  'iconFilter': string;
  'iconMap': string;
  'iconMapSelected': string;
  'iconMenuSwitch': string;
  'icon_add': string;
  'icon_block': string;
  'icon_block_selected': string;
  'icon_canlendar': string;
  'icon_canlendar_selected': string;
  'icon_check': string;
  'icon_detail': string;
  'icon_detail_selected': string;
  'icon_filter': string;
  'icon_map': string;
  'icon_map_selected': string;
  'icon_menu_switch': string;
  'toolBar': string;
  'viewBar': string;
}
declare const cssExports: CssExports;
export = cssExports;
