// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'control': string;
  'count': string;
  'entryitem': string;
  'entrylist': string;
  'name': string;
  'status': string;
}
declare const cssExports: CssExports;
export = cssExports;
