// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'contentpreview': string;
  'contentquota': string;
  'date': string;
  'dateday': string;
  'dateweek': string;
  'entrycontent': string;
  'entrydate': string;
  'entryimgview': string;
  'entryitem': string;
  'listdate': string;
  'listentry': string;
  'listitem': string;
}
declare const cssExports: CssExports;
export = cssExports;
